# permissions for end users to view egressgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressgateway-viewer-role
rules:
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways/status
  verbs:
  - get
