# permissions for end users to edit egressgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressgateway-editor-role
rules:
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways/status
  verbs:
  - get
