
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgatewayclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgatewayclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - egressgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tcproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x-k8s.io
  resources:
  - tcproutes/status
  verbs:
  - get
  - patch
  - update
