apiVersion: networking.x-k8s.io/v1alpha1
kind: EgressGateway
metadata:
  name: egressgateway
spec:
  class: cilium-egressgatewayclass
  nonMasqueradeCIDRs:
  - 10.0.0.0/8
  masqueradeIP: 192.168.0.100

